let data=MTV.loadData(),role=sessionStorage.getItem("mtvRole")||"Админ",tab="dashboard",editing=null,authToken=sessionStorage.getItem("mtvAuth")||"";
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function persist(msg="Сохранено"){MTV.saveData(data);render();toast(msg)}
function canManage(){return role!=="Модератор"}
function uid(prefix){return prefix+"_"+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function field(id,label,value="",area=false){return '<label class="afield"><span>'+MTV.esc(label)+'</span>'+(area?'<textarea id="'+id+'" rows="4">'+MTV.esc(value)+'</textarea>':'<input id="'+id+'" value="'+MTV.esc(value)+'">')+'</label>'}
function openModal(title,html,onSave){editing=onSave;$("#modalTitle").textContent=title;$("#modalBody").innerHTML=html;$("#modal").classList.add("open")}
function closeModal(){editing=null;$("#modal").classList.remove("open")}
$("#modalClose").onclick=closeModal;
$("#modalSave").onclick=()=>{if(!editing)return;editing();closeModal();persist()};
function dashboard(){const publishedNews=data.news.filter(n=>n.published!==false).length,publishedProjects=data.programs.filter(n=>n.published!==false).length,chars=(localStorage.getItem("mtvData")||"").length;return '<div class="hero-mini"><div><div class="eyebrow">MTV STUDIO · CONTROL ROOM</div><h1>САЙТ<br>ПОД КОНТРОЛЕМ<span>.</span></h1><p>Управляй публикациями, проектами, страницами и настройками из одной панели.</p></div><div class="quick"><a href="index.html" class="qcard"><small>Сайт</small><b>Открыть ↗</b></a><a href="news.html" class="qcard"><small>Новости</small><b>Просмотр ↗</b></a><a href="projects.html" class="qcard"><small>Проекты</small><b>Просмотр ↗</b></a></div></div><div class="statsrow"><div><b>'+data.news.length+'</b><span>новостей</span><em>'+publishedNews+' опубликовано</em></div><div><b>'+data.programs.length+'</b><span>проектов</span><em>'+publishedProjects+' опубликовано</em></div><div><b>'+data.team.length+'</b><span>сотрудников</span><em>роли редакции</em></div><div><b>'+chars+'</b><span>символов</span><em>локальный контент</em></div></div><div class="panel-grid"><section class="panel"><div class="panel-head"><h2>Быстрые действия</h2></div><div class="actiongrid"><button onclick="tab=\'news\';render()">＋ Новость</button><button onclick="tab=\'projects\';render()">＋ Проект</button><button onclick="tab=\'content\';render()">✎ Главный экран</button><button onclick="tab=\'settings\';render()">⚙ Настройки</button></div></section><section class="panel"><div class="panel-head"><h2>Режим</h2></div><p class="hint">Роль: <b>'+MTV.esc(role)+'</b>. Данные хранятся в <code>localStorage</code> этого браузера.</p><p class="hint">Контент текущей версии хранится локально в браузере. Для общей редакционной базы и совместного редактирования нужен отдельный backend-хранилище.</p></section></div>'}
function contentTab(){return '<section class="panel"><div class="panel-head"><h2>Главный экран</h2><button class="accentbtn" onclick="saveContent()">Сохранить изменения</button></div>'+field("heroTag","Надзаголовок",data.heroTag)+field("heroTitle","Заголовок",data.heroTitle,true)+field("heroText","Описание",data.heroText,true)+'</section><section class="panel"><div class="panel-head"><h2>Базовые настройки</h2></div>'+field("siteName","Название сайта",data.siteName)+field("ticker","Бегущая строка",data.ticker)+field("footerText","Текст подвала",data.footerText,true)+field("copyright","Копирайт",data.copyright)+'<div class="buttonrow"><button class="accentbtn" onclick="saveBase()">Сохранить</button></div></section>'}
function saveContent(){if(!canManage())return toast("Недостаточно прав");data.heroTag=$("#heroTag").value;data.heroTitle=$("#heroTitle").value;data.heroText=$("#heroText").value;persist("Главный экран сохранён")}
function saveBase(){if(!canManage())return toast("Недостаточно прав");data.siteName=$("#siteName").value;data.ticker=$("#ticker").value;data.footerText=$("#footerText").value;data.copyright=$("#copyright").value;persist("Настройки сохранены")}
function newsTab(){return '<section class="panel"><div class="panel-head"><div><h2>Новости</h2><p class="hint">Поиск, редактирование, публикация и дублирование.</p></div><button class="accentbtn" onclick="newNews()">＋ Добавить</button></div><div class="toolbar"><input id="newsQuery" class="searchbox" placeholder="Поиск по заголовку, рубрике..."><span class="count">'+data.news.length+' всего</span></div><div id="newsRows"></div></section>'}
function newsRows(){const q=($("#newsQuery")?.value||"").toLowerCase();const arr=data.news.filter(n=>[n.title,n.category,n.body].join(" ").toLowerCase().includes(q));$("#newsRows").innerHTML=arr.map(n=>'<div class="itemrow"><div class="thumb" style="background:'+MTV.esc(n.color||"linear-gradient(135deg,#2a224b,#ec4d9e)")+'">'+MTV.esc(n.art||"MTV")+'</div><div class="itemmain"><b>'+MTV.esc(n.title)+'</b><span>'+MTV.esc(n.category||"MTV NEWS")+' · '+MTV.esc(n.date||"без даты")+'</span></div><span class="badge '+(n.published!==false?"published":"draft")+'">'+(n.published!==false?"LIVE":"DRAFT")+'</span><div class="rowactions"><button onclick="editNews(\''+n.id+'\')">Изменить</button><button onclick="toggleNews(\''+n.id+'\')">'+(n.published!==false?"Скрыть":"Опубликовать")+'</button><button onclick="duplicateNews(\''+n.id+'\')">Дубль</button><button class="danger" onclick="deleteNews(\''+n.id+'\')">Удалить</button></div></div>').join("")||'<div class="empty">Ничего не найдено.</div>';$("#newsQuery").oninput=newsRows}
function newNews(){if(!canManage())return toast("Недостаточно прав");openModal("Новая новость",field("mCategory","Рубрика","MTV NEWS")+field("mTitle","Заголовок")+field("mBody","Текст","",true)+field("mArt","Символ","MTV")+field("mColor","Градиент CSS","linear-gradient(135deg,#2a224b,#ec4d9e)")+field("mDate","Дата",new Date().toLocaleDateString("ru-RU")),()=>{data.news.unshift({id:uid("n"),category:$("#mCategory").value||"MTV NEWS",title:$("#mTitle").value.trim()||"Без заголовка",body:$("#mBody").value,art:$("#mArt").value||"MTV",color:$("#mColor").value,date:$("#mDate").value,published:true,featured:false})})}
function editNews(id){if(!canManage())return toast("Недостаточно прав");const n=data.news.find(x=>x.id===id);if(!n)return;openModal("Редактировать новость",field("mCategory","Рубрика",n.category)+field("mTitle","Заголовок",n.title)+field("mBody","Текст",n.body,true)+field("mArt","Символ",n.art)+field("mColor","Градиент CSS",n.color||"")+field("mDate","Дата",n.date||""),()=>{n.category=$("#mCategory").value;n.title=$("#mTitle").value.trim()||n.title;n.body=$("#mBody").value;n.art=$("#mArt").value;n.color=$("#mColor").value;n.date=$("#mDate").value})}
function toggleNews(id){const n=data.news.find(x=>x.id===id);if(!n)return;n.published=n.published===false;persist(n.published?"Новость опубликована":"Новость скрыта")}
function duplicateNews(id){if(!canManage())return toast("Недостаточно прав");const n=data.news.find(x=>x.id===id);data.news.unshift({...MTV.clone(n),id:uid("n"),title:n.title+" · копия",published:false});persist("Копия создана")}
function deleteNews(id){if(!canManage())return toast("Недостаточно прав");if(!confirm("Удалить новость?"))return;data.news=data.news.filter(n=>n.id!==id);persist("Новость удалена")}
function projectsTab(){return '<section class="panel"><div class="panel-head"><div><h2>Проекты</h2><p class="hint">Карточки проектов и их публикация.</p></div><button class="accentbtn" onclick="newProject()">＋ Добавить</button></div><div id="projectRows"></div></section>'}
function projectRows(){const box=$("#projectRows");box.innerHTML=data.programs.map(p=>'<div class="itemrow plain"><div class="itemmain"><b>'+MTV.esc(p.title)+'</b><span>'+MTV.esc(p.number||"PROJECT")+'</span></div><span class="badge '+(p.published!==false?"published":"draft")+'">'+(p.published!==false?"LIVE":"DRAFT")+'</span><div class="rowactions"><button onclick="editProject(\''+p.id+'\')">Изменить</button><button onclick="toggleProject(\''+p.id+'\')">'+(p.published!==false?"Скрыть":"Опубликовать")+'</button><button class="danger" onclick="deleteProject(\''+p.id+'\')">Удалить</button></div></div>')}
function newProject(){if(!canManage())return toast("Недостаточно прав");openModal("Новый проект",field("mNumber","Номер","04 / NEW")+field("mTitle","Название")+field("mBody","Описание","",true),()=>data.programs.push({id:uid("p"),number:$("#mNumber").value,title:$("#mTitle").value.trim()||"Новый проект",body:$("#mBody").value,published:true}))}
function editProject(id){if(!canManage())return toast("Недостаточно прав");const p=data.programs.find(x=>x.id===id);if(!p)return;openModal("Редактировать проект",field("mNumber","Номер",p.number)+field("mTitle","Название",p.title)+field("mBody","Описание",p.body,true),()=>{p.number=$("#mNumber").value;p.title=$("#mTitle").value.trim()||p.title;p.body=$("#mBody").value})}
function toggleProject(id){const p=data.programs.find(x=>x.id===id);if(!p)return;p.published=p.published===false;persist(p.published?"Проект опубликован":"Проект скрыт")}
function deleteProject(id){if(!canManage())return toast("Недостаточно прав");if(confirm("Удалить проект?")){data.programs=data.programs.filter(p=>p.id!==id);persist("Проект удалён")}}
function pagesTab(){return '<section class="panel"><div class="panel-head"><h2>О канале</h2><button class="accentbtn" onclick="savePages()">Сохранить</button></div>'+field("aboutText","Описание канала",data.aboutText,true)+'</section><section class="panel"><div class="panel-head"><h2>Контакты</h2></div>'+field("email","Email",data.email)+field("telegramMtv","Telegram MTV",data.telegramMtv)+field("telegramNextv","Telegram NEXTV",data.telegramNextv)+'<div class="buttonrow"><button class="accentbtn" onclick="savePages()">Сохранить контакты</button></div></section>'}
function savePages(){if(!canManage())return toast("Недостаточно прав");data.aboutText=$("#aboutText").value;data.email=$("#email").value;data.telegramMtv=$("#telegramMtv").value;data.telegramNextv=$("#telegramNextv").value;persist("Страницы сохранены")}
function teamTab(){return '<section class="panel"><div class="panel-head"><div><h2>Команда</h2><p class="hint">Список сотрудников и ролей редакции.</p></div><button class="accentbtn" onclick="newTeam()">＋ Добавить</button></div>'+data.team.map(u=>'<div class="itemrow plain"><div class="itemmain"><b>'+MTV.esc(u.name)+'</b><span>'+MTV.esc(u.role)+'</span></div><div class="rowactions">'+(role==="Создатель"&&u.role!=="Создатель"?'<button class="danger" onclick="deleteTeam(\''+u.id+'\')">Удалить</button>':"")+'</div></div>').join("")+'</section>'}
function newTeam(){if(role!=="Создатель")return toast("Только создатель может менять команду");openModal("Новый сотрудник",field("mName","Имя / логин")+field("mRole","Роль","Админ"),()=>data.team.push({id:uid("u"),name:$("#mName").value.trim()||"Сотрудник",role:$("#mRole").value||"Админ"}))}
function deleteTeam(id){if(role!=="Создатель")return toast("Нет прав");data.team=data.team.filter(u=>u.id!==id);persist("Сотрудник удалён")}
function telegramTab(){return '<section class="panel"><div class="panel-head"><div><h2>Telegram Live</h2><p class="hint">Источники: @nextv_itv и @mtv_1russia. Сайт проверяет новые публикации каждые 5 секунд.</p></div><button class="accentbtn" onclick="syncTelegramNow()">Обновить сейчас</button></div><div id="tgStatus" class="hint">Проверка соединения…</div><div id="tgItems"></div></section>'}
async function syncTelegramNow(){const box=$("#tgStatus");try{box.textContent="Получаю последние публикации…";const r=await fetch("/api/telegram-news?ts="+Date.now(),{cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Ошибка Telegram");box.textContent="Соединение активно · обновлено "+new Date(j.updatedAt||Date.now()).toLocaleTimeString("ru-RU");$("#tgItems").innerHTML=(j.items||[]).slice(0,12).map(n=>'<div class="itemrow plain"><div class="itemmain"><b>'+MTV.esc(n.title)+'</b><span>'+MTV.esc(n.source||"Telegram")+' · '+MTV.esc(n.date||"")+(n.sourceUrl?' · <a href="'+MTV.esc(n.sourceUrl)+'" target="_blank" rel="noopener">открыть ↗</a>':"")+'</span></div></div>').join("")||'<div class="empty">Пока нет новых публикаций.</div>'}catch(e){box.textContent="Telegram пока недоступен: "+e.message}}
function settingsTab(){return '<section class="panel"><div class="panel-head"><h2>Внешний вид</h2><button class="accentbtn" onclick="saveSettings()">Сохранить</button></div><p class="hint">Акцент применяется ко всем публичным страницам.</p><div class="themegrid"><label><input type="radio" name="accent" value="lime" '+(data.accent==="lime"||!data.accent?"checked":"")+'> Лайм</label><label><input type="radio" name="accent" value="pink" '+(data.accent==="pink"?"checked":"")+'> Розовый</label><label><input type="radio" name="accent" value="blue" '+(data.accent==="blue"?"checked":"")+'> Синий</label></div></section><section class="panel"><div class="panel-head"><h2>Данные</h2></div><div class="actiongrid"><button onclick="exportJson()">↓ Экспорт JSON</button><label class="uploadbtn">↑ Импорт JSON<input type="file" accept="application/json" onchange="importJson(event)" hidden></label><button onclick="resetData()">↺ Сбросить исходный контент</button><button onclick="clearData()">⌫ Очистить localStorage</button></div><p class="hint">Импорт полностью заменяет текущий контент в этом браузере.</p></section>'}
function saveSettings(){if(!canManage())return toast("Недостаточно прав");data.accent=document.querySelector('input[name="accent"]:checked')?.value||"lime";persist("Настройки сохранены")}
function exportJson(){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mtv-content.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importJson(e){if(!canManage())return toast("Недостаточно прав");const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result);if(!parsed.news||!parsed.programs)throw new Error();data=Object.assign(MTV.clone(MTV.DEFAULT_DATA),parsed);persist("Импортировано")}catch(err){toast("Не удалось импортировать JSON")}};r.readAsText(file)}
function resetData(){if(!canManage())return toast("Недостаточно прав");if(confirm("Сбросить все локальные изменения?")){data=MTV.clone(MTV.DEFAULT_DATA);persist("Исходный контент восстановлен")}}
function clearData(){if(!canManage())return toast("Недостаточно прав");if(confirm("Очистить локальные данные?")){localStorage.removeItem("mtvData");data=MTV.clone(MTV.DEFAULT_DATA);render();toast("Локальные данные очищены")}}
function render(){const body=$("#workspace"),titles={dashboard:"Обзор",content:"Контент",news:"Новости",projects:"Проекты",pages:"Страницы",team:"Команда",settings:"Настройки"};$("#pageTitle").textContent=titles[tab];$$("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));body.innerHTML=tab==="dashboard"?dashboard():tab==="content"?contentTab():tab==="news"?newsTab():tab==="projects"?projectsTab():tab==="pages"?pagesTab():tab==="telegram"?telegramTab():tab==="team"?teamTab():settingsTab();if(tab==="news")newsRows();if(tab==="projects")projectRows();if(tab==="telegram")syncTelegramNow();document.body.style.setProperty("--accent",data.accent==="pink"?"#ff2f93":data.accent==="blue"?"#69b7ff":"#d8ff3f")}
async function checkSession(){if(!authToken)return false;try{const r=await fetch("/api/studio-auth",{headers:{Authorization:"Bearer "+authToken}});if(!r.ok)throw new Error();const j=await r.json();role=j.role||"Админ";sessionStorage.setItem("mtvRole",role);$("#roleSelect").textContent=role.toUpperCase();return true}catch(e){sessionStorage.removeItem("mtvAuth");authToken="";return false}}
async function doLogin(e){e.preventDefault();const u=$("#loginUser").value.trim(),p=$("#loginPass").value;try{const r=await fetch("/api/studio-auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:u,password:p})}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Неверный логин или пароль");authToken=j.token;role=j.role||"Админ";sessionStorage.setItem("mtvAuth",authToken);sessionStorage.setItem("mtvRole",role);$("#login").classList.remove("open");$("#roleSelect").textContent=role.toUpperCase();render()}catch(e){toast(e.message||"Не удалось войти")}}
$("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
$("#loginForm").onsubmit=doLogin;const logout=()=>{sessionStorage.removeItem("mtvAuth");sessionStorage.removeItem("mtvRole");location.reload()};$("#logout").onclick=logout;$("#logoutTop")?.addEventListener("click",logout);
(async()=>{const ok=await checkSession();if(!ok)$("#login").classList.add("open");render()})();
