const DEFAULT_DATA={
siteName:"MTV Россия",ticker:"MTV РОССИЯ · МУЗЫКА. КУЛЬТУРА. СЕЙЧАС.",heroTag:"MTV ORIGINALS · 2026",
heroTitle:"ГРОМЧЕ.\nСМЕЛЕЕ.\nБЛИЖЕ.",heroText:"Музыка, люди и истории, которые задают настроение. Новый ритм MTV Россия.",
aboutText:"MTV — пространство музыки и поп-культуры, где важны новые голоса, смелые идеи и люди, которые меняют правила.",
footerText:"Музыка. Культура. Сейчас. Следи за обновлениями и присоединяйся к сообществу.",
email:"hello@mtv.example",telegramMtv:"https://t.me/mtv_1russia",telegramNextv:"https://t.me/nextv_itv",copyright:"© 2026 MTV Россия · Концепт сайта",accent:"lime",
ads:[{id:"ad1",badge:"РЕКЛАМА",title:"ГЛАВНЫЕ НОВОСТИ ВСЕГДА ПОД РУКОЙ",description:"Подписывайтесь на наш канал в Телеграм",image:"",buttonText:"Подробнее",buttonUrl:"https://t.me/mtv_1russia",active:true}],news:[
{id:"n1",category:"MTV NEWS",title:"Новый сезон начинается с громкого сигнала",body:"Новости музыки, поп-культуры и новых творческих проектов — в одном месте.",art:"MTV",color:"linear-gradient(135deg,#2a224b,#ec4d9e)",date:"08.10.2026",published:true,featured:true,buttonText:"Подробнее"},
{id:"n2",category:"ВИДЕО · ПРЕМЬЕРА",title:"На повторе: треки, которые задают настроение",body:"Подборка редакции для тех, кто всегда на своей частоте.",art:"▶",color:"linear-gradient(135deg,#0b3c55,#42d9db)",date:"07.10.2026",published:true,featured:false,buttonText:"Подробнее"},
{id:"n3",category:"КУЛЬТУРА · ГИД",title:"Что добавить в культурный плейлист",body:"Открытия, события и идеи для следующего большого впечатления.",art:"★",color:"linear-gradient(135deg,#572015,#ff9a39)",date:"05.10.2026",published:true,featured:false,buttonText:"Подробнее"}
],
programs:[
{id:"p1",title:"MTV Originals",body:"Истории за пределами плейлиста.",number:"01 / ORIGINALS",published:true},
{id:"p2",title:"Music Radar",body:"Новые имена и музыкальные открытия.",number:"02 / MUSIC",published:true},
{id:"p3",title:"Culture Club",body:"Люди, идеи и культурные повороты.",number:"03 / CULTURE",published:true}
],
team:[{id:"u1",name:"MTVA",role:"Создатель"},{id:"u2",name:"Редакция",role:"Админ"},{id:"u3",name:"Модератор",role:"Модератор"}]
};
function clone(o){return JSON.parse(JSON.stringify(o))}
function loadData(){try{const raw=JSON.parse(localStorage.getItem("mtvData"));if(raw&&typeof raw==="object")return Object.assign(clone(DEFAULT_DATA),raw)}catch(e){}return clone(DEFAULT_DATA)}
function saveData(data){localStorage.setItem("mtvData",JSON.stringify(data))}
function esc(value=""){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function active(name){return location.pathname.split("/").pop()===name?"active":""}
function nav(){const links='<a class="'+active("news.html")+'" href="news.html">Новости</a><a class="'+active("projects.html")+'" href="projects.html">Проекты</a><a class="'+active("about.html")+'" href="about.html">О канале</a><a class="'+active("contacts.html")+'" href="contacts.html">Контакты</a><a href="admin.html">Studio</a>';return '<div class="container"><div class="nav"><a class="logo" href="index.html">MTV<b>.</b></a><nav class="navlinks">'+links+'</nav><span class="status">● В РИТМЕ</span><button type="button" class="mobile-menu" onclick="document.body.classList.toggle(\'menu-open\')">☰</button><div class="mobile-panel">'+links+'</div></div></div>'}
function footer(data){return '<footer class="footer"><div class="container"><div class="footer-top"><div><a class="logo" href="index.html">MTV<b>.</b></a><p style="max-width:520px">'+esc(data.footerText)+'</p></div></div><small>'+esc(data.copyright)+'</small></div></footer>'}
function shell(data){document.documentElement.style.setProperty("--accent",data.accent==="pink"?"#ff2f93":data.accent==="blue"?"#69b7ff":"#d8ff3f");const top=document.getElementById("siteTopline");if(top)top.textContent=data.ticker;const n=document.getElementById("siteNav");if(n)n.innerHTML=nav();const f=document.getElementById("siteFooter");if(f)f.innerHTML=footer(data);document.title=data.siteName+" — MTV"}
function getAds(data){return Array.isArray(data.ads)?data.ads.filter(a=>a.active!==false):[]}
function renderAds(data){const box=document.getElementById("adsHome");if(!box)return;const ads=getAds(data);if(!ads.length){box.innerHTML="";return}const ad=ads[0];box.innerHTML='<section class="promo-wrap"><div class="promo" style="'+(ad.image?'background-image:linear-gradient(90deg,#09090ccc,#09090c22),url("'+esc(ad.image)+'")':'background-image:linear-gradient(120deg,#2a0a33,#ff5d1d,#f6aa18)')+'"><div class="promo-copy"><div class="promo-badge">'+esc(ad.badge||"РЕКЛАМА")+'</div><h2>'+esc(ad.title||"")+'</h2><p>'+esc(ad.description||"")+'</p>'+(ad.buttonText?'<a class="promo-button" href="'+esc(ad.buttonUrl||"#")+'" target="_blank" rel="noopener">'+esc(ad.buttonText)+' ↗</a>':"")+'</div></div></section>'}
function initIndex(){const d=loadData();shell(d);document.getElementById("heroTag").textContent=d.heroTag;document.getElementById("heroTitle").innerHTML=esc(d.heroTitle).replace(/\n/g,"<br>");document.getElementById("heroText").textContent=d.heroText;renderAds(d)}
function injectNewsModal(){if(document.getElementById("newsModal"))return;document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="newsModal" role="dialog" aria-modal="true" aria-label="Подробнее"><div class="modal-card"><button class="modal-close" id="newsModalClose" aria-label="Закрыть">×</button><div id="newsModalMedia"></div><div class="modal-copy"><div class="meta" id="newsModalMeta"></div><h2 id="newsModalTitle"></h2><div id="newsModalBody"></div><div class="news-date" id="newsModalDate"></div><a class="cta" id="newsModalButton" href="#" target="_blank" rel="noopener" style="display:none">Открыть ↗</a></div></div></div>');document.getElementById("newsModalClose").onclick=()=>document.getElementById("newsModal").classList.remove("open");document.getElementById("newsModal").addEventListener("click",e=>{if(e.target.id==="newsModal")e.currentTarget.classList.remove("open")});document.addEventListener("keydown",e=>{if(e.key==="Escape")document.getElementById("newsModal")?.classList.remove("open")})}
function openNews(item){injectNewsModal();const m=document.getElementById("newsModal"),media=document.getElementById("newsModalMedia");document.getElementById("newsModalMeta").textContent=item.category||"MTV NEWS";document.getElementById("newsModalTitle").textContent=item.title||"Без заголовка";document.getElementById("newsModalBody").innerHTML=esc(item.body||"").replace(/\n/g,"<br>");document.getElementById("newsModalDate").textContent=(item.date||"Без даты")+(item.source?" · "+item.source:"");media.innerHTML="";if(item.mediaType==="video"&&item.mediaUrl){media.innerHTML='<video class="news-media" src="'+esc(item.mediaUrl)+'" controls playsinline preload="metadata"></video>'}else if(item.mediaType==="photo"&&item.mediaUrl){media.innerHTML='<img class="news-media" src="'+esc(item.mediaUrl)+'" alt="" loading="eager">'}else{media.innerHTML='<div class="news-art big-art" style="background:'+esc(item.color||"linear-gradient(135deg,#2a224b,#ec4d9e)")+'"><div class="letter">'+esc(item.art||"MTV")+'</div></div>'}const btn=document.getElementById("newsModalButton");if(item.buttonUrl){btn.href=item.buttonUrl;btn.style.display="inline-flex";btn.textContent=item.buttonText||"Открыть ↗"}else btn.style.display="none";m.classList.add("open")}
function mergeTelegram(items){const local=JSON.parse(localStorage.getItem("mtvTelegramNews")||"[]");const map=new Map(local.map(x=>[x.id,x]));for(const item of items||[])map.set(item.id,Object.assign(map.get(item.id)||{},item));const merged=[...map.values()].sort((a,b)=>(b.timestamp||0)-(a.timestamp||0)).slice(0,100);localStorage.setItem("mtvTelegramNews",JSON.stringify(merged));return merged}
function loadTelegramLocal(){try{const list=JSON.parse(localStorage.getItem("mtvTelegramNews"));return Array.isArray(list)?list:[]}catch(e){return[]}}
function renderNews(){
const d=loadData();shell(d);injectNewsModal();const grid=document.getElementById("newsGrid"),search=document.getElementById("newsSearch"),filters=document.getElementById("newsFilters");let category="ALL";let items=[...loadTelegramLocal(),...d.news.filter(n=>n.published!==false)].filter((n,i,a)=>a.findIndex(x=>x.id===n.id)<i===false);
function drawFilters(){const cats=["ALL",...new Set(items.map(n=>n.category||"MTV NEWS"))];filters.innerHTML=cats.map(c=>'<button class="filter '+(c==="ALL"?"active":"")+'" data-cat="'+esc(c)+'">'+esc(c==="ALL"?"Все":c)+'</button>').join("")+'<span id="liveStatus" class="filter" style="cursor:default">● LIVE · TELEGRAM</span>'}
function draw(){const q=search.value.trim().toLowerCase();const visible=items.filter(n=>!q||[n.title,n.body,n.category,n.source].join(" ").toLowerCase().includes(q)).filter(n=>category==="ALL"||n.category===category);grid.innerHTML=visible.length?visible.map(n=>'<article class="news-card"><div class="news-art" style="background:'+esc(n.color||"linear-gradient(135deg,#2a224b,#ec4d9e)")+'">'+(n.mediaType?'<div class="media-badge">'+(n.mediaType==="video"?"▶ VIDEO":"● PHOTO")+'</div>':"")+'<div class="letter">'+esc(n.art||"MTV")+'</div></div><div class="news-body"><div class="meta">'+esc(n.category||"MTV NEWS")+'</div><h3>'+esc(n.title||"Без заголовка")+'</h3><p>'+esc((n.body||"").slice(0,190))+(String(n.body||"").length>190?"…":"")+'</p><div class="news-date">'+esc(n.date||"Без даты")+(n.source?" · "+esc(n.source):"")+'</div><button class="cta news-more" data-news-id="'+esc(n.id)+'">'+esc(n.buttonText||"Подробнее")+' ↗</button></div></article>').join(""):'<div class="empty">По вашему запросу ничего не найдено.</div>';grid.querySelectorAll("[data-news-id]").forEach(b=>b.onclick=()=>{const n=items.find(x=>x.id===b.dataset.newsId);if(n?.buttonUrl)window.open(n.buttonUrl,"_blank","noopener");else if(n)openNews(n)})}
async function syncTelegram(){try{const offset=Number(localStorage.getItem("mtvTelegramOffset")||"0");const r=await fetch("/api/telegram-news?offset="+offset+"&ts="+Date.now(),{cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Telegram unavailable");if(Array.isArray(j.items)&&j.items.length){const tg=mergeTelegram(j.items);items=[...tg,...d.news.filter(n=>n.published!==false)];items=items.filter((n,i,a)=>a.findIndex(x=>x.id===n.id)===i)}if(Number.isFinite(j.nextOffset))localStorage.setItem("mtvTelegramOffset",String(j.nextOffset));drawFilters();category="ALL";draw();const st=document.getElementById("liveStatus");if(st)st.textContent="● LIVE · "+new Date(j.updatedAt||Date.now()).toLocaleTimeString("ru-RU")}catch(e){const st=document.getElementById("liveStatus");if(st)st.textContent="○ TELEGRAM · ожидание";draw()}}
filters.onclick=e=>{const b=e.target.closest("[data-cat]");if(!b)return;category=b.dataset.cat;filters.querySelectorAll("[data-cat]").forEach(x=>x.classList.toggle("active",x===b));draw()};search.oninput=draw;drawFilters();draw();syncTelegram();setInterval(syncTelegram,5000);
}
function renderProjects(){const d=loadData();shell(d);document.getElementById("projectGrid").innerHTML=d.programs.filter(p=>p.published!==false).map(p=>'<article class="project-card"><div class="project-body"><div class="project-number">'+esc(p.number||"MTV PROJECT")+'</div><div><h3>'+esc(p.title||"Проект MTV")+'</h3><p>'+esc(p.body||"")+'</p></div></div></article>').join("")||'<div class="empty">Пока нет опубликованных проектов.</div>'}
function renderAbout(){const d=loadData();shell(d);document.getElementById("aboutText").textContent=d.aboutText}
function renderContacts(){const d=loadData();shell(d);document.getElementById("emailLink").href="mailto:"+d.email;document.getElementById("emailText").textContent=d.email;document.getElementById("mtvLink").href=d.telegramMtv;document.getElementById("nextvLink").href=d.telegramNextv}
window.MTV={DEFAULT_DATA,clone,loadData,saveData,esc,initIndex,renderNews,renderProjects,renderAbout,renderContacts,openNews,renderAds,getAds};
